### ISSUE TITLE
进入购票界面后还需勾选用户协议，要多加一层if判断并勾选

### ISSUE THREAD

**Issue by EruilWuid** [Hobr/cp_deprecate#12]
成功进入购票页面后，还需要勾选（同意并阅读bilibili购票服务协议）

![ZA7CD22{1H5O4MD(F72)DJ7](https://user-images.githubusercontent.com/117145809/233834935-82a9caac-dcf6-44c0-b8aa-603cefc74c84.png)

**Comment by yasdiox** [comment]
在bilibili.py的第62行后添加`WebDriver.find_element(By.CLASS_NAME, "check-icon").click()`应该就可以解决了

**Comment by EruilWuid** [comment]
谢谢，这样确实可以实现勾选，但是还需要判断一下是否勾选，否则循环里会重复勾选取消，但我不太清楚这个函数返回值是什么，怎么判断是否已经勾选。

**Comment by yasdiox** [comment]
勾选后就会直接下单 应该不会有这种问题吧

**Comment by yasdiox** [comment]
我并不会Python 也许可以在最后再加上一段`WebDriver.find_element(By.CLASS_NAME, "check-icon").click()`

**Comment by EruilWuid** [comment]
确实是个可行的好方法，但是我好像已经不用考虑这个问题了，勾选过一次后以后进支付页面好像会自动勾选，之前第一次测脚本的时候没有选中导致在那空循环，现在只要进就是自动勾选的状态了。

**Comment by EruilWuid** [comment]
不过要是这么解决还是有点问题的，如果这次b站自动帮你勾选了用户协议，那就等于每次进循环都没勾选了。

**Comment by yasdiox** [comment]
这么看来是的 我并不知道B站会帮我自动勾选 希望作者能解决这个小问题

**Comment by linxxyi** [comment]
啊啊啊老哥我刚刚第一次刷进购买界面，加了那行代码自动没有勾选，票没抢到

**Comment by yasdiox** [comment]
那真是抱歉（

**Comment by Hobr** [comment]
我的锅，最初这个脚本是边改边用的，当时发现勾选过后不用再选，我就把那行代码直接删了，后来也就忘了还有这个问题。。

**Comment by Small-tailqwq** [comment]
啊，是否可以在获取登陆cookie时点击一遍？然后后续购买界面应该就是默认点击了。（比较方便）
（或者是每次开始抢票运行前先打开一遍其他漫展的票，确认是否已勾选，如未勾选则勾选，已勾选的话跳过，开始循环抢票）（比较保险）

**Comment by Hobr** [comment]
> 啊，是否可以在获取登陆cookie时点击一遍？然后后续购买界面应该就是默认点击了。（比较方便）

不知道b站的机制是啥样的，目前来看第二种方法比较可靠，稍后我试一试

**Comment by Small-tailqwq** [comment]
> > 啊，是否可以在获取登陆cookie时点击一遍？然后后续购买界面应该就是默认点击了。（比较方便）
> 
> 不知道b站的机制是啥样的，目前来看第二种方法比较可靠，稍后我试一试

提供一点可能不可靠的信息（X）
我以前没在会员购买过票，所以默认是没勾选的。昨天看见这个issues之后用程序打开的调试chrome进入购买页面，手动勾选同意之后下单（未付款，后取消）。之后那个调试的chrome就默认勾选了。
今天用不同电脑测试您的代码，同b站账号，使用调试的chrome，经过观察也是默认勾选。
刚才使用第一台电脑，同b站账号，使用edge浏览器，经过观察同样是默认勾选。
既然电脑不同浏览器也不同，我觉得应该是跟着账号走的。等待更多测试。
如果是跟着账号走的话，那么第二种方法也只需要在 `更变/第一次获取/第一次添加` cookie时验证一遍就ok了。后续重复启停就可以不再验证。

**Comment by Hobr** [comment]
> > > 啊，是否可以在获取登陆cookie时点击一遍？然后后续购买界面应该就是默认点击了。（比较方便）
> > 
> > 
> > 不知道b站的机制是啥样的，目前来看第二种方法比较可靠，稍后我试一试
> 
> 提供一点可能不可靠的信息（X） 我以前没在会员购买过票，所以默认是没勾选的。昨天看见这个issues之后用程序打开的调试chrome进入购买页面，手动勾选同意之后下单（未付款，后取消）。之后那个调试的chrome就默认勾选了。 今天用不同电脑测试您的代码，同b站账号，使用调试的chrome，经过观察也是默认勾选。 刚才使用第一台电脑，同b站账号，使用edge浏览器，经过观察同样是默认勾选。 既然电脑不同浏览器也不同，我觉得应该是跟着账号走的。等待更多测试。 如果是跟着账号走的话，那么第二种方法也只需要在 `更变/第一次获取/第一次添加` cookie时验证一遍就ok了。后续重复启停就可以不再验证。

我试了一下，也是如此，在获取cookie那一步顺便随便找个展子勾选一下，问题就解决了。感谢提供思路。

**Comment by araea** [comment]
> > > > 啊，是否可以在获取登陆cookie时点击一遍？然后后续购买界面应该就是默认点击了。（比较方便）
> > > 
> > > 
> > > 不知道b站的机制是啥样的，目前来看第二种方法比较可靠，稍后我试一试
> > 
> > 
> > 提供一点可能不可靠的信息（X） 我以前没在会员购买过票，所以默认是没勾选的。昨天看见这个issues之后用程序打开的调试chrome进入购买页面，手动勾选同意之后下单（未付款，后取消）。之后那个调试的chrome就默认勾选了。 今天用不同电脑测试您的代码，同b站账号，使用调试的chrome，经过观察也是默认勾选。 刚才使用第一台电脑，同b站账号，使用edge浏览器，经过观察同样是默认勾选。 既然电脑不同浏览器也不同，我觉得应该是跟着账号走的。等待更多测试。 如果是跟着账号走的话，那么第二种方法也只需要在 `更变/第一次获取/第一次添加` cookie时验证一遍就ok了。后续重复启停就可以不再验证。
> 
> 我试了一下，也是如此，在获取cookie那一步顺便随便找个展子勾选一下，问题就解决了。感谢提供思路。

我刚刚去试了一下，会员购随便找个展勾选协议之后，刷新再进入刚刚点的那个展，我这边的情况是未勾选？

**Comment by Hobr** [comment]
> > > > > 啊，是否可以在获取登陆cookie时点击一遍？然后后续购买界面应该就是默认点击了。（比较方便）
> > > > 
> > > > 
> > > > 不知道b站的机制是啥样的，目前来看第二种方法比较可靠，稍后我试一试
> > > 
> > > 
> > > 提供一点可能不可靠的信息（X） 我以前没在会员购买过票，所以默认是没勾选的。昨天看见这个issues之后用程序打开的调试chrome进入购买页面，手动勾选同意之后下单（未付款，后取消）。之后那个调试的chrome就默认勾选了。 今天用不同电脑测试您的代码，同b站账号，使用调试的chrome，经过观察也是默认勾选。 刚才使用第一台电脑，同b站账号，使用edge浏览器，经过观察同样是默认勾选。 既然电脑不同浏览器也不同，我觉得应该是跟着账号走的。等待更多测试。 如果是跟着账号走的话，那么第二种方法也只需要在 `更变/第一次获取/第一次添加` cookie时验证一遍就ok了。后续重复启停就可以不再验证。
> > 
> > 
> > 我试了一下，也是如此，在获取cookie那一步顺便随便找个展子勾选一下，问题就解决了。感谢提供思路。
> 
> 我刚刚去试了一下，会员购随便找个展勾选协议之后，刷新再进入刚刚点的那个展，我这边的情况是未勾选？

啊这。。。。搞不懂阿b了

**Comment by Hobr** [comment]
可以通过判断下单按键`confirm-paybtn`的class是否包含`active`来帮助勾选,我新开的repo里会去解决这个问题
