### ISSUE TITLE
config.json中关于cookie的添加和邮箱的设置格式能否详细说明一下

### ISSUE THREAD

**Issue by Hikalight** [Hobr/cp_deprecate#17]
config.json中关于cookie的添加和邮箱的设置格式能否详细说明一下

**Comment by Hobr** [comment]
cookie不用自己设置，启动时脚本可以帮你获取

"send_email"为true时启用邮箱提示，sender、password、receiver就分别是发件人邮箱、密码、收件人邮箱

**Comment by donghaidiwang** [comment]
邮件发送失败如何解决

**Comment by donghaidiwang** [comment]
刚去查了然后开了smtp,把密码那一栏换成了授权码，但是还是失败

**Comment by Hobr** [comment]
> 刚去查了然后开了smtp,把密码那一栏换成了授权码，但是还是失败

具体原因我也不清楚，这个是 @mdjso 做的，我到目前也没有用过邮箱提醒，你可以和他讨论讨论

**Comment by Hobr** [comment]
邮件提示功能将合并到新repo里，selenium也可以通过寻找元素来判断是否下单，但是之前迟迟没做，将在新的项目里实现
