### ISSUE TITLE
运行一段时间后就会被屏蔽访问，要重新运行程序，有啥解决方法咩？

### ISSUE THREAD

**Issue by Keke-nA** [Hobr/cp_deprecate#18]

**Comment by Hobr** [comment]
~~增加sleep时间~~

**Comment by gary886** [comment]
> 

我不太懂，有没有可能增加一个类似五分钟重新运行一次抢票程序之类的另一个程序

**Comment by Hobr** [comment]
b站有风控机制，创建订单时要请求api`https://show.bilibili.com/api/ticket/order/createV2`，频率过高就会banip返回代码412，只能通过增加时间间隔或者无限切换ip地址来解决，我本来还做了个多线程，结果也只会导致更快地被封
