### ISSUE TITLE
新上传的b站抢票代码运行几秒后就会闪退

### ISSUE THREAD

**Issue by simo0n3** [Hobr/cp_deprecate#24]
大佬一开始接入cookie和选择抢票日期都没问题，但之后每运行几秒就会闪退

**Comment by Hobr** [comment]
浏览器里是不是一直都出现小电视，那应该是刷新太快被b站风控，只能换个ip再来

**Comment by simo0n3** [comment]
我把页面最大化后这个问题貌似就解决了0.0

**Comment by Hobr** [comment]
> 我把页面最大化后这个问题貌似就解决了0.0

啊？？？不过现在的点击时间间隔有点短，很容易被风控，我好几个ip已经被拿下了，可以修改第67行`uniform(0.6, 1.2)`，感觉0.6-1.2秒还是有点太快了

**Comment by simo0n3** [comment]
emmm大佬你是对的，应该确实是风控问题。我把刷新时间调大并换了ip才好
