### ISSUE TITLE
出现“验证已过期，请返回详情页重新下单”后闪退

### ISSUE THREAD

**Issue by simo0n3** [Hobr/cp_deprecate#25]
出现“验证已过期，请返回详情页重新下单”后闪退。换ip也无法解决

**Comment by simo0n3** [comment]
![image](https://user-images.githubusercontent.com/120444000/235303040-79638a5f-0824-413e-b610-65669abf6139.png)

**Comment by Hobr** [comment]
一个小时前b站开始处理卡进下单页的行为，在获取token的api里会返回验证页面，这个脚本暂时失效了

**Comment by Hobr** [comment]
这是我给一帮没计算机语言基础的人写的教程，相关的代码稍后写

https://github.com/Hobr/cp_deprecate/blob/main/解决验证问题的方法.pdf
