### ISSUE TITLE
找不到相应的CSS元素

### ISSUE THREAD

**Issue by xmbhjQAQ** [Hobr/cp_deprecate#26]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".confirm-paybtn.active"}
  (Session info: MicrosoftEdge=112.0.1722.58)

**Comment by Hobr** [comment]
这种应该就是被风控了，无限显示小电视，换个ip，调整一下刷新时间间隔

代码不完善，没有增加相关的判断
